// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraductorBasico.Infrastructure.Context;

#nullable disable

namespace TraductorBasico.Infrastructure.Migrations
{
    [DbContext(typeof(TraductorBasicoDataContext))]
    partial class TraductorBasicoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraductorBasico.Domain.Entities.Frase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Español")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronunciacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Frases");
                });

            modelBuilder.Entity("TraductorBasico.Domain.Entities.FraseImagen", b =>
                {
                    b.Property<int>("FraseId")
                        .HasColumnType("int");

                    b.Property<int>("ImagenId")
                        .HasColumnType("int");

                    b.HasKey("FraseId", "ImagenId");

                    b.HasIndex("ImagenId");

                    b.ToTable("FraseImagenes");
                });

            modelBuilder.Entity("TraductorBasico.Domain.Entities.ImagenDiccionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("ImagenesDiccionario");
                });

            modelBuilder.Entity("TraductorBasico.Domain.Entities.FraseImagen", b =>
                {
                    b.HasOne("TraductorBasico.Domain.Entities.Frase", "Frase")
                        .WithMany("FraseImagenes")
                        .HasForeignKey("FraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraductorBasico.Domain.Entities.ImagenDiccionario", "Imagen")
                        .WithMany("FraseImagenes")
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frase");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("TraductorBasico.Domain.Entities.Frase", b =>
                {
                    b.Navigation("FraseImagenes");
                });

            modelBuilder.Entity("TraductorBasico.Domain.Entities.ImagenDiccionario", b =>
                {
                    b.Navigation("FraseImagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
